# Site settings
author: Chung Trịnh
title: Chung Trịnh's blog
email: aschungtv@gmail.com	
description: Chung Trịnh, Trịnh Văn Chung, SQL Server, C#, Tutorials, Windows, WPF, Windows Phone
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chungtrinh.com" # the base hostname & protocol for your site
twitter_username: trinhvanchung
github_username:  

# Google Analytics
google_analytics_tracking_id: UA-62079859-1

#
# Jekyll Settings
#
paginate: 20
paginate_path: "page/:num"
category_dir: categories

# Build settings
markdown: kramdown
